export const htmlElements = {
    sexBreakdown: {
        chartContainer: document.querySelector('#sexDivide__chartContainer'),
        controller: document.querySelector('#sexBreakdown__controller'),
        loader: document.querySelector('.pieContainer__loaderContainer--sexBreakdown'),
        listButton: document.querySelector('.hamburger--sexbreakdownList'),
        list: document.querySelector('.scrollableList--sexbreakdownList'),
    },
    minmax:{
        controller: document.querySelector('#minmax__controller'),
        elements:{
            maleMax: document.querySelector('.minmaxBox__item--maxMale'),
            maleMin: document.querySelector('.minmaxBox__item--minMale'),
            femaleMax: document.querySelector('.minmaxBox__item--maxFemale'),
            femaleMin: document.querySelector('.minmaxBox__item--minFemale'),
        },
        loaders: [...document.querySelectorAll('.shoesContainer__loaderContainer')],
    },
    priceLevel:{
        chartContainer: document.querySelector('#priceLevel__chartContainer'),
        variablesController: document.querySelector('#priceLevel__variablesQueryController'),
        sortController: document.querySelector('#priceLevel__sortQueryController'),
        loader: document.querySelector('.priceLevelBox__loaderContainer'),
    }
};

export const uiLabels = {
    'wszystkie':'Wszystkie',
    'klapki-i-sandaly': 'Klapki/sandały', 
    'polbuty': 'Pólbuty', 
    'kozaki-i-inne': 'Kozaki i inne', 
    'sportowe':'Sportowe',
    "japonki":'Japonki',
    "klapki":'Klapki',
    "sandaly":'Sandały',
    "kapcie":'Kapcie',
    "codzienne":'Codzienne',
    "wizytowe":'Wizytowe',
    "glany":'Glany',
    "trampki":'Trampki',
    "buty-trekkingowe-i-trapery":'Trekkingowe',
    "sneakersy":'Sneakersy',
    "mokasyny":'Mokasyny',
    "espadryle":'Espadryle',
    "kalosze":'Kalosze',
    "trekkingi-i-trapery":'Trapery',
    "kozaki":'Kozaki',
    "trzewiki":'Trzewiki',
    "sztyblety":'Sztyblety',
    "sniegowce":'Śniegowce',
    "bieganie":'Do biegania',
    "buty-do-wody":'Buty do wody',
    "fitness":'Fitness',
    "halowki":'Halówki',
    "pilka-nozna":'Piłka nożna',
    "koszykowka":'Koszykówka',
    "tenis":'Tenis',
    "koturny":'Koturny',
    "na-obcasie":'Na obcasie',
    "na-koturnie":'Na koturnie',
    "baleriny":'Baleriny',
    "szpilki":'Szpliki',
    "lordsy":'Lordsy',
    "eleganckie":'Eleganckie',
    "plaskie":'Płaskie',
    "oxfordy":"Oxfordy",
    "botki":'Botki',
    "emu":'Emu',
    "ugg":'Ugg',
    "oficerki":'Oficerki',
    "muszkieterki":'Muszkieterki',
    "kowbojki":'Kowbojki',
    "trampki-i-tenisowki":'Trampki',
}